### ISSUE TITLE
REST API for spy

### ISSUE THREAD

**Issue by divisuals** [linsong/sedona#11]
Currently, spyWeblet (servlet) serves simple, fixed web (HTML) pages. By serving only the data (JSON) using REST APIs, the presentation would be decoupled from data, offering greater flexibility on client side (REST/ JSON can feed another web application for mobile/ desktop use.

**Comment by divisuals** [comment]
Initial RESTWeblet (spy) is committed on branch. 

Few (future) enhancements:
- Fix paths displayed or remove it completely. (Unlike HTML, the end-points are not clickable anyway)
- Add authentication to both spy and REST
- Create a light-weight UI to test the end-points

**Comment by linsong** [comment]
since this had been merged, I will close this issue now.
