### ISSUE TITLE
Not able to run mqtt at runtime

### ISSUE THREAD

**Issue by titusece** [linsong/sedona#16]
Hi,
Always we need to modify the mqtt.sax file for creating a new publisher or subscriper and messages.
Why not able to allow drag and drop to sedona workspace to create publisher or subscriper and setting port, host name etc., ?
If do that, getting "Disconnected" and "Invalide parent" error.

**Comment by linsong** [comment]
you will need to create a MQTTService object first, then create Subscriber and Publisher as its children, and then create Message objects as children of Subscriber or Publisher object.

BTW, the communityMQTT kit is not production ready yet, I am still working on some stability issues. Pls let me know if you find any issue, thanks.

**Comment by titusece** [comment]
Hi Linsong,
Firstly, thank you so much for the reply.
Yes, I just drag and dropped the "MQTTService object" first then I drag and dropped the "Subscriber" in Sedona.

> _you will need to create a MQTTService object first, then create Subscriber and Publisher as its children, and then create Message objects as children of Subscriber or Publisher object._

Yes,I did the same in .sax file and compiled to .sab file then its fine but I requirement would be need to create or drag and drop the "MQTTService" and "Subscriber" then "Message" for that.
So, I have to modify the .sax file for every time when I need to create a new Subscriper or Publish with Message ?
If yes, can you pleas explain how ??
Can you please help me on this issue ?

I'm trying to create a Subscriber and want to publish from Linux PC.

I'm testing the MQTT in sedona, surely I let you know the issues if any.

Thanks for replying.

**Comment by titusece** [comment]
Dear Vincent,

Initially I just created the following sax file which has Subscribr alone with its children Message.
After running the sedona, I need to create a new Publisher with its children Message.

Once I drag and dropped the new "Publisher" object to sedona workspace and it shows the status as "Disconnected" and Error as "Invalid parent"
How do we create new Objects (Publisher or Subscriber) at run time ?

![initial](https://cloud.githubusercontent.com/assets/973452/15966611/850b5cb0-2f41-11e6-9e36-a46c382716d7.png)
I used the commands to publish to Sedona's subscriber.

mosquitto_pub -d -h 192.168.8.5 -t titus/int -m 9
mosquitto_pub -d -h 192.168.8.5 -t titus/float -m 9.99

![after_publish_in_linuxpc](https://cloud.githubusercontent.com/assets/973452/15966628/996e2f98-2f41-11e6-9208-3509beed14bf.png)

**Comment by linsong** [comment]
You need to create objects follow the below hierarchy: 
![screen shot 2016-06-11 at 12 44 44](https://cloud.githubusercontent.com/assets/36017/15983197/6610b85a-2fd2-11e6-8da5-6b89cd1073a6.png)

Create MQTTService object first, then create Subscriber or Publisher object as MQTTServer object's children and config host, port clientid; then create FloatMessage/IntMessage/BoolMessage etc message objects as Subscriber or Publisher object's children and config message's topic etc.

Publisher object's children: 
![screen shot 2016-06-11 at 12 49 46](https://cloud.githubusercontent.com/assets/36017/15983221/014c0680-2fd3-11e6-865a-3fc6a4584e04.png)

Subscriber object's children: 
![screen shot 2016-06-11 at 12 50 29](https://cloud.githubusercontent.com/assets/36017/15983229/2e800912-2fd3-11e6-8014-564a845d79b7.png)

**Comment by titusece** [comment]
Dear Vincent,
Thanks you so much for the reply!
Let me try and update to you.

Regards,
Titus S.

**Comment by titusece** [comment]
Dear Vincent,
_

> You need to create objects follow the below hierarchy:

_ 

How did you create this ?
In sedona workbench or changing the mqtt.sax file ?

Thanks for the support.

Regards,
Titus S.

**Comment by linsong** [comment]
Hi Titus,

  I create these objects in CPT Tools. But in theory, you can create these objects by modifying mqtt.sax file directly, although that will be very error prone.

**Comment by titusece** [comment]
Hi Vincent,
Thanks for your reply.
Actually my requirement is that not to modify the mqtt.sax file but need to create everything (publisher, subscriber, message etc.,) in run time....like just drag and drop the objects in sedona workspace and need to wire it.

Please share your thoughts on this if you have any.
Thanks again.

Regards,
Titus S.

**Comment by linsong** [comment]
hi @titusece, kind of confused. do you want to generate the mqtt objects in code automatically ?

**Comment by titusece** [comment]
Hi Vincent,
Sorry for that confusion.
I meant, typically we will drag and drop the objects in sedona workspace, 
say ex: If we need Constant float value then we will drag and drop the "ConstFloat" object from "Types"

I'm using WEBPro and Sedona application Editor" tool.

Regards,
Titus S.

**Comment by linsong** [comment]
@titusece so you want to know how to build the mqtt component objects in SAE ? If yes, please refer to my second comment in this thread

**Comment by linsong** [comment]
close this ticket since there is no comments for long time
