### ISSUE TITLE
use master as main development branch

### ISSUE THREAD

**Issue by AndreySV** [linsong/sedona#37]
I suggest to merge develop into master, drop develop and use master as main development branch.

1. Master branch is default landing branch if user opens project page. So he see latest news, development activity and can decide whether project is active. Currently 
2. It's recommended practice: [github flow](https://guides.github.com/introduction/flow/)
3. Github counts developer contributions based on commits merged into [master branch](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile):
4. It's easier for user to find what branch to take, when a lot of active and stale branches are exist in the project.

**Comment by linsong** [comment]
Agreed, this will be better to let others know the progress of the project. We can make some change: 
1. get rid of *develop* branch, use *master* as the new develop branch, all new change should branch from *master* branch
2. create a *stable* branch to only contain stable features for others to use
3. changes in *master* branch will be merged to *stable* branch before every release

I can make the change if no other comments.

**Comment by AndreySV** [comment]
Please do.

**Comment by linsong** [comment]
From now on, we should use *master* branch as the base branch for development, branch from it when you want to develop a new feature, and *master* branch is still the user landing branch; *stable* branch is for stable codes,  *master* branch will be merged to *stable* branch periodically, before every release. The old *develop* branch has been removed, and we should not use it anymore.
