### ISSUE TITLE
import old project development history

### ISSUE THREAD

**Issue by AndreySV** [linsong/sedona#38]
I don't know why old development history was not imported as project was migrated to git. It's certainly possible. For example, it's already done [here](https://github.com/vancepym/sedona-1.2).

1. It make project to look more mature, when number of commits on master branch is 1000+ instead of 40+.
2. Sometimes it's useful to look into project's history: git blame/log.

**Comment by linsong** [comment]
If I remember correctly, when I tried to migrate the old commit history from hg to git, but failed. I will give it another try to see if this is still possible.

**Comment by AndreySV** [comment]
You can skip the work and take import done in this repo: https://github.com/vancepym/sedona-1.2

**Comment by linsong** [comment]
Yeah, that's an option. I need to take a look on what's the best way to do it in git.

**Comment by linsong** [comment]
@AndreySV  @divisuals the good news is: the old commit history has been imported; the bad news is something is broken.

To avoid lots of possible conflicts, I deleted *develop* branch and recreated it to based on old commit history, but this action causes related pull requests removed. You will need to recreate your branch based on *master* branch, one possible way: 

* git fetch 
* git branch -m develop-sys-improvements develop-sys-improvements-old
* git checkout -b develop-sys-improvements origin/master 
* git cherry-pic COMMITS_FROM_YOUR_BRANCH

Now *master* branch will be used as base branch for development, *stable* branch is used to track stable codes.

Let me know if you have anything unclear.

**Comment by AndreySV** [comment]
broken things are expected. From git point of view this is completely new repository now.
All forks will be broken as well. But because we don't get any contributions from there (hopefully yet), IMHO there will not be any problem there.
