### ISSUE TITLE
MQTT client kit 

### ISSUE THREAD

**Issue by linsong** [linsong/sedona#8]
MQTT is a machine-to-machine (M2M)/"Internet of Things" connectivity protocol. It's lightweight and open protocol, more details here: http://mqtt.org/

This task will develop a MQTT client kit on sedona platform.

**Comment by divisuals** [comment]
Great addition! I think the protocol could probably be implemented as a communication 'driver' or could ride over DASP, just like SOX.

Another good addition is CoAP (https://tools.ietf.org/html/rfc7252)

**Comment by linsong** [comment]
I plan to implement the kit as a simple sedona wrapper based on MQTT C library (http://www.eclipse.org/paho/clients/c/embedded/). It is easier to be implemented compared to code it in sedona totally.

CoAP seems good, will give it a try.

**Comment by linsong** [comment]
since mqtt kit had been moved to be a [standalone repository](https://github.com/linsong/sedona-mqtt), I close this issue now.
