### ISSUE TITLE
clean-up the dev environment - repo, tests, etc

### ISSUE THREAD

**Issue by divisuals** [linsong/sedona#9]
Few specific clean-ups planned:
- java, sedona and native source is scattered across the 'src' directory; should be aggregated into few logical folders
- temp directories (manifests, kits, out, test, etc) are generated in the project root folder, should be generated in 'build' or 'dist' folder
- test compiled code (.ir) is in the kit's main folder rather than in respective '/test' folders
- all tests are currently run together rather than individually

**Comment by linsong** [comment]
let's will make things a lot easier, I am confused at the source code directory almost all the time. And run test individually will be very helpful to debug a specific test.

**Comment by divisuals** [comment]
Found out that a mechanism to run individual sedonac tests exists but isn't working properly. For example, one can specify a single test as:
```
sedonac -test sedonac.test.AppTest 
```
svm tests are all run together for now, so both of these need fixing.

**Comment by divisuals** [comment]
Have another switch ```-utest arg``` defined and working for svm tests where the argument can be a specific test, a specific type or a kit.

Also, updated the message on screen - didn't realize that most of the verifies is from a single test in hvac!
```
svm scode/x86-test.scode -utest hvac::LSeqTest.test
```
gives **54944 verifies!** Will commit and create a pull request shortly.

**Comment by divisuals** [comment]
Seems the merge is good so closing the issue.
